// SKILL ALIAS MAP
// Maps canonical skill name -> known PDF/resume variants
export const SKILL_ALIASES: Record<string, string[]> = {
  react: ["reactjs", "react.js", "react js"],
  node: ["nodejs", "node.js", "node js"],
  "next.js": ["nextjs", "next js", "next"],
  vue: ["vuejs", "vue.js", "vue js"],
  typescript: ["ts", "type script"],
  javascript: ["js", "java script"],
  postgresql: ["postgres", "psql", "pg"],
  mongodb: ["mongo", "mongo db"],
      graphql: ["graph ql", "graph-ql"],
  "rest api": ["restapi", "rest apis", "restful api", "restful", "rest"],
  css: ["css3", "cascading style sheets"],
  html: ["html5", "hypertext markup"],
  aws: ["amazon web services", "amazon aws"],
  gcp: ["google cloud platform", "google cloud"],
  azure: ["microsoft azure"],
  "ci/cd": ["cicd", "ci cd", "continuous integration", "continuous deployment"],
  docker: ["dockerfile", "docker container"],
  kubernetes: ["k8s", "kube"],
  tailwind: ["tailwindcss", "tailwind css"],
  express: ["expressjs", "express.js"],
  django: ["django rest", "django framework"],
  fastapi: ["fast api"],
  redis: ["redis cache"],
  elasticsearch: ["elastic search", "elastic"],
  tensorflow: ["tensor flow"],
  pytorch: ["torch", "py torch"],
  sql: ["mysql", "mssql", "sql server"],
  git: ["github", "gitlab", "version control"],
  linux: ["unix", "ubuntu", "bash", "shell scripting"],
  flutter: ["dart flutter"],
  "react native": ["reactnative"],
  "spring boot": ["springboot", "spring framework"],
};
